### ISSUE TITLE
It seems that MPI is not really needed cause it is used only in logger

### ISSUE THREAD

**Issue by Erichliu00** [jonasrothfuss/ProMP#1]
Hey, you say `Many components of the Meta-RL algorithm are parallelized either using either MPI or Tensorflow in order to ensure efficient use of all CPU cores.` in the document but MPI is only found in logger which means that it is not necessarily used since codes won't be exected in MPI. Am I missing something?

**Comment by jonasrothfuss** [comment]
Thanks a lot for this hint! I was pretty convinced that the vec_env_executor which can run many Mujoco simulator sessions in different OS processes was implemented with MPI. However, you're right, the message passing is handled with the python multiprocessing module. As soon as I have time I can try to remove the MPI dependency from the logger, since it's pretty much unnecessary.

Since it's your suggestions, I'd also highly appreciate if you remove the MPI dependency and make a corresponding pull request.

Thanks again for the tip and let me know!

**Comment by Erichliu00** [comment]
Well, if you mean [this kind of vec_env_executor](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py), it relies on multiprocessing instead of MPI4PY. I agree with you that the code would be accelerated if use vectorized env or use MPI4PY to run multiple Mujoco in parallel and communicate samples and gradient between workers. Will do when I have time. Thanks for your response!
